version: '3.8'

services:
  backend-test:
    container_name: backend-test
    build: ./
    ports:
      - 8090:8090
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: 'redis:latest'
    env_file:
      - .env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
