version: '3.8'

services:
  avito-backend-test:
    image: avito-backend-test
    container_name: avito-backend-test
    build: ./
    command: ./wait-for-postgres.sh db ./avito-backend-test
    ports:
      - 8090:8090
    depends_on:
      - db
    env_file:
      - .env


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
