postgres:
  host:     "localhost"
  port:     "5432"
  username: "postgres"
  dbname:   "postgres"
  SSLMode:  "disable"

redis:
  addr: "redis:6379"

http:
  port:           8090
  maxHeaderBytes: 1
  readTimeout:    10s
  writeTimeout:   10s
