postgres:
  host:     "localhost"
  port:     "5432"
  username: "postgres"
  dbname:   "postgres"
  SSLMode:  "disable"

#http:
#  port: 8090
#  maxHeaderBytes: 1
#  readTimeout: 10s
#  writeTimeout: 10s
#

#cache:
#  ttl: 3600s


#limiter:
#  rps: 10
#  burst: 4
#  ttl: 1000m