state:
  database: "mongo"

postgres:
  host:     "localhost"
  port:     "5432"
  username: "postgres"
  dbname:   "postgres"
  SSLMode:  "disable"
  migration:

mongo:
  host:
  port:
  username:
  database:
  authDB:

redis:
  addr: "redis:6379"

http:
  port:           8090
  maxHeaderBytes: 1
  readTimeout:    10s
  writeTimeout:   10s
